name: CI - Build with Vite and Save Artifact

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build project with Vite
        run: npm run build

      - name: Archive artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/